{"cveId": "CVE-2022-29222", "cwe": ["CWE-295", "CWE-295"], "cvss": [{"baseScore": "5.9", "version": "3.1", "Attack Vector": "None", "Attack Complexity": "High", "Privileges Required": "None", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "None", "Integrity Impact": "High", "Availability Impact": "None"}], "references": ["https://github.com/pion/dtls/security/advisories/GHSA-w45j-f832-hxvh", "https://github.com/pion/dtls/commit/d2f797183a9f044ce976e6df6f362662ca722412", "https://github.com/pion/dtls/releases/tag/v2.1.5"], "description": ["Pion DTLS is a Go implementation of Datagram Transport Layer Security. Prior to version 2.1.5, a DTLS Client could provide a Certificate that it doesn't posses the private key for and Pion DTLS wouldn't reject it. This issue affects users that are using Client certificates only. The connection itself is still secure. The Certificate provided by clients can't be trusted when using a Pion DTLS server prior to version 2.1.5. Users should upgrade to version 2.1.5 to receive a patch. There are currently no known workarounds."], "published": "2022-05-21T00:15:12.047", "state": "PUBLIC", "vendorName": ["pion"], "productName": ["dtls"], "github": {"advisories": ["https://github.com/pion/dtls/security/advisories/GHSA-w45j-f832-hxvh"], "commits": ["https://github.com/pion/dtls/commit/d2f797183a9f044ce976e6df6f362662ca722412"], "pocAdvisorie": {}, "repo": "https://github.com/pion/dtls/", "info": {"exist": true, "topics": ["dtls", "encryption", "go", "golang", "pion", "pion-dtls", "psk", "tls-ecdhe-ecdsa", "tls-ecdhe-rsa", "udp"], "langs": {"Go": 717806, "Dockerfile": 270}, "avatar": "https://avatars.githubusercontent.com/u/38192892?v=4", "stargazers": 624, "language": "Go"}}, "pocList": []}