{"cveId": "CVE-2017-16531", "cwe": ["CWE-119", "CWE-119"], "cvss": [{"baseScore": "6.6", "version": "3.1", "Attack Vector": "Physical", "Attack Complexity": "Low", "Privileges Required": "Low", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "High", "Integrity Impact": "High", "Availability Impact": "High"}], "references": ["https://lists.debian.org/debian-lts-announce/2017/12/msg00004.html", "https://usn.ubuntu.com/3754-1/", "https://groups.google.com/d/msg/syzkaller/hP6L-m59m_8/Co2ouWeFAwAJ", "http://www.securityfocus.com/bid/102025", "https://github.com/torvalds/linux/commit/bd7a3fe770ebd8391d1c7d072ff88e9e76d063eb", "https://www.oracle.com/technetwork/security-advisory/cpuoct2019-5072832.html"], "description": ["drivers/usb/core/config.c in the Linux kernel before 4.13.6 allows local users to cause a denial of service (out-of-bounds read and system crash) or possibly have unspecified other impact via a crafted USB device, related to the USB_DT_INTERFACE_ASSOCIATION descriptor."], "published": "2017-11-04T01:29:36.943", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["n/a"], "github": {"advisories": [], "commits": ["https://github.com/torvalds/linux/commit/bd7a3fe770ebd8391d1c7d072ff88e9e76d063eb"], "pocAdvisorie": null, "repo": "https://github.com/torvalds/linux/", "info": {"exist": true, "topics": [], "langs": {"C": 1348363240, "Assembly": 9632676, "Shell": 5140958, "Python": 3111393, "Makefile": 2734946, "Perl": 1223890, "Rust": 1035407, "Roff": 203501, "C++": 179456, "SmPL": 166781, "Yacc": 128635, "Lex": 72476, "Awk": 71808, "Jinja": 30138, "UnrealScript": 16878, "Gherkin": 10932, "Linker Script": 9830, "M4": 3329, "Clojure": 2621, "MATLAB": 2482, "sed": 2433, "XS": 1239, "RPC": 962}, "avatar": "https://avatars.githubusercontent.com/u/1024025?v=4", "stargazers": 191042, "language": "C"}}, "pocList": []}