{"cveId": "CVE-2017-1000433", "cwe": ["CWE-287", "CWE-287"], "cvss": [{"baseScore": "8.1", "version": "3.1", "Attack Vector": "None", "Attack Complexity": "High", "Privileges Required": "None", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "High", "Integrity Impact": "High", "Availability Impact": "High"}], "references": ["https://lists.debian.org/debian-lts-announce/2018/07/msg00000.html", "https://github.com/rohe/pysaml2/issues/451", "https://security.gentoo.org/glsa/201801-11", "https://lists.debian.org/debian-lts-announce/2021/02/msg00038.html"], "description": ["pysaml2 version 4.4.0 and older accept any password when run with python optimizations enabled. This allows attackers to log in as any user without knowing their password."], "published": "2018-01-02T23:29:00.337", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["n/a"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}