{"cveId": "CVE-2018-14625", "cwe": ["CWE-416", "CWE-416", "CWE-362", "CWE-416", "CWE-362"], "cvss": [{"baseScore": "4.4", "version": "2.0", "Attack Vector": "Low", "Attack Complexity": "M", "Privileges Required": "None", "User Interaction": "None", "Scope": "None", "Confidentiality Impact": "Partial", "Integrity Impact": "P", "Availability Impact": "P"}], "references": ["https://usn.ubuntu.com/3871-1/", "https://usn.ubuntu.com/3871-3/", "https://usn.ubuntu.com/3871-4/", "https://usn.ubuntu.com/3871-5/", "https://access.redhat.com/errata/RHSA-2019:2029", "https://access.redhat.com/errata/RHSA-2019:2043", "https://access.redhat.com/errata/RHSA-2019:4154", "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14625", "https://lists.debian.org/debian-lts-announce/2019/05/msg00002.html", "https://syzkaller.appspot.com/bug?extid=bd391451452fb0b93039", "https://usn.ubuntu.com/3872-1/", "https://usn.ubuntu.com/3878-1/", "https://usn.ubuntu.com/3878-2/"], "description": ["A flaw was found in the Linux Kernel where an attacker may be able to have an uncontrolled read to kernel-memory from within a vm guest. A race condition between connect() and close() function may allow an attacker using the AF_VSOCK protocol to gather a 4 byte information leak or possibly intercept or corrupt AF_VSOCK messages destined to other clients."], "published": "2018-09-10T13:29:00.277", "state": "PUBLIC", "vendorName": ["[UNKNOWN]"], "productName": ["kernel"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}