{"cveId": "CVE-2024-31919", "cwe": ["CWE-770", "CWE-770", "CWE-770"], "cvss": [{"baseScore": "5.9", "version": "3.1", "Attack Vector": "None", "Attack Complexity": "High", "Privileges Required": "None", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "None", "Integrity Impact": "None", "Availability Impact": "High"}], "references": ["https://www.ibm.com/support/pages/node/7157979", "https://exchange.xforce.ibmcloud.com/vulnerabilities/290259"], "description": ["IBM MQ 9.0 LTS, 9.1 LTS, 9.2 LTS, 9.3 LTS and 9.3 CD, in certain configurations, is vulnerable to a denial of service attack caused by an error processing messages when an API Exit using MQBUFMH is used.  IBM X-Force ID:  290259."], "published": "2024-06-28T18:15:03.940", "state": "PUBLIC", "vendorName": ["IBM"], "productName": ["MQ"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}