{"cveId": "CVE-2024-56596", "cwe": ["CWE-129", "CWE-129"], "cvss": [{"baseScore": "7.8", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "Low", "Privileges Required": "Low", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "High", "Integrity Impact": "High", "Availability Impact": "High"}], "references": ["https://git.kernel.org/stable/c/b62f41aeec9d250144c53875b507c1d45ae8c8fc", "https://git.kernel.org/stable/c/97e693593162eef6851d232f0c8148169ed46a5c", "https://git.kernel.org/stable/c/9efe72eefd4c4a7ce63b3e4d667d766d2b360cb4", "https://git.kernel.org/stable/c/ff9fc48fab0e1ea0d423c23c99b91bba178f0b05", "https://git.kernel.org/stable/c/e7d376f94f72b020f84e77278b150ec1cc27502c", "https://git.kernel.org/stable/c/8ff7579554571d92e3deab168f5a7d7b146ed368", "https://git.kernel.org/stable/c/839f102efb168f02dfdd46717b7c6dddb26b015e"], "description": ["In the Linux kernel, the following vulnerability has been resolved:\n\njfs: fix array-index-out-of-bounds in jfs_readdir\n\nThe stbl might contain some invalid values. Added a check to\nreturn error code in that case."], "published": "2024-12-27T15:15:18.963", "state": "PUBLIC", "vendorName": ["Linux"], "productName": ["Linux"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}