{"cveId": "CVE-2018-10911", "cwe": ["CWE-190", "CWE-200", "CWE-502", "CWE-502", "CWE-190", "CWE-200", "CWE-502", "CWE-502"], "cvss": [{"baseScore": "7.5", "version": "3.1", "Attack Vector": "None", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "High", "Integrity Impact": "None", "Availability Impact": "None"}], "references": ["https://review.gluster.org/#/c/glusterfs/+/21067/", "https://access.redhat.com/errata/RHSA-2018:2607", "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10911", "https://lists.debian.org/debian-lts-announce/2018/09/msg00021.html", "https://access.redhat.com/errata/RHSA-2018:2608", "https://access.redhat.com/errata/RHSA-2018:3470", "https://access.redhat.com/errata/RHSA-2018:2892", "https://access.redhat.com/errata/RHSA-2018:3242", "https://security.gentoo.org/glsa/201904-06", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00035.html", "https://lists.debian.org/debian-lts-announce/2021/11/msg00000.html"], "description": ["A flaw was found in the way dic_unserialize function of glusterfs does not handle negative key length values. An attacker could use this flaw to read memory from other locations into the stored dict value."], "published": "2018-09-04T14:29:00.220", "state": "PUBLIC", "vendorName": ["Red Hat"], "productName": ["glusterfs:"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}