{"cveId": "CVE-2023-0795", "cwe": ["CWE-125", "CWE-125", "CWE-125", "CWE-125"], "cvss": [{"baseScore": "6.8", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "Low", "Integrity Impact": "None", "Availability Impact": "High"}], "references": ["https://gitlab.com/libtiff/libtiff/-/issues/493", "https://gitlab.com/libtiff/libtiff/-/commit/afaabc3e50d4e5d80a94143f7e3c997e7e410f68", "https://gitlab.com/gitlab-org/cves/-/blob/master/2023/CVE-2023-0795.json", "https://lists.debian.org/debian-lts-announce/2023/02/msg00026.html", "https://www.debian.org/security/2023/dsa-5361", "https://security.netapp.com/advisory/ntap-20230316-0003/", "https://security.gentoo.org/glsa/202305-31"], "description": ["LibTIFF 4.4.0 has an out-of-bounds read in tiffcrop in tools/tiffcrop.c:3488, allowing attackers to cause a denial-of-service via a crafted tiff file. For users that compile libtiff from sources, the fix is available with commit afaabc3e."], "published": "2023-02-13T23:15:11.727", "state": "PUBLIC", "vendorName": ["libtiff"], "productName": ["libtiff"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}