{"cveId": "CVE-2021-28038", "cwe": ["CWE-770", "CWE-770"], "cvss": [{"baseScore": "6.5", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "Low", "Privileges Required": "Low", "User Interaction": "None", "Scope": "Complete", "Confidentiality Impact": "None", "Integrity Impact": "None", "Availability Impact": "High"}], "references": ["http://xenbits.xen.org/xsa/advisory-367.html", "http://www.openwall.com/lists/oss-security/2021/03/05/1", "https://lists.debian.org/debian-lts-announce/2021/03/msg00010.html", "https://lists.debian.org/debian-lts-announce/2021/03/msg00035.html", "https://security.netapp.com/advisory/ntap-20210409-0001/", "https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=2991397d23ec597405b116d96de3813420bdcbc3"], "description": ["An issue was discovered in the Linux kernel through 5.11.3, as used with Xen PV. A certain part of the netback driver lacks necessary treatment of errors such as failed memory allocations (as a result of changes to the handling of grant mapping errors). A host OS denial of service may occur during misbehavior of a networking frontend driver. NOTE: this issue exists because of an incomplete fix for CVE-2021-26931."], "published": "2021-03-05T18:15:13.127", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["n/a"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}