{"cveId": "CVE-2019-20916", "cwe": ["CWE-22", "CWE-22"], "cvss": [{"baseScore": "7.5", "version": "3.1", "Attack Vector": "None", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "None", "Integrity Impact": "High", "Availability Impact": "None"}], "references": ["https://github.com/pypa/pip/issues/6413", "https://github.com/gzpan123/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace", "https://github.com/pypa/pip/compare/19.1.1...19.2", "https://lists.debian.org/debian-lts-announce/2020/09/msg00010.html", "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00005.html", "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00010.html", "https://www.oracle.com/security-alerts/cpuapr2022.html", "https://www.oracle.com/security-alerts/cpujul2022.html"], "description": ["The pip package before 19.2 for Python allows Directory Traversal when a URL is given in an install command, because a Content-Disposition header can have ../ in a filename, as demonstrated by overwriting the /root/.ssh/authorized_keys file. This occurs in _download_http_url in _internal/download.py."], "published": "2020-09-04T20:15:11.013", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["n/a"], "github": {"advisories": [], "commits": ["https://github.com/gzpan123/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace"], "pocAdvisorie": null, "repo": "https://github.com/gzpan123/pip/", "info": {"exist": true, "topics": [], "langs": {"Python": 6045565, "HTML": 3983}, "avatar": "https://avatars.githubusercontent.com/u/8546511?v=4", "stargazers": 0, "language": "Python"}}, "pocList": []}